version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - image: circleci/mysql:5.7-ram

    steps:
      - checkout

      - run: |
          mysql -u root -h 127.0.0.1 -D circle_test -e"SELECT Host, User, Password FROM mysql.user;"
