version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - image: circleci/mysql:5.7-ram

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
