version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:5.7-ram
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          
    working_directory: ~/work

    steps:
      - checkout

      - run:
          command: ls; pwd; ls /usr/bin; ls /usr/sbin; cat /etc/issue; ls
      - run:
          command: apt-get update && apt-get -y install procps wget sudo
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          command: ps -ef | grep mysqld
      - run: 
          command: mysql -u root -h 127.0.0.1 -D circle_test -e"SELECT Host, User FROM mysql.user;"
