version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:5.7-ram
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          
    working_directory: ~/laravel

    steps:
      - checkout

      - run:
          command: ls; pwd; ls /usr/bin; ls /usr/sbin; cat /etc/issue
      - run:
          command: apt-get update && apt-get -y install procps 
      - run:
          command: ps -ef | grep mysqld
      - run: 
          command: mysql -u root -h 127.0.0.1 -D circle_test -e"SELECT Host, User, Password FROM mysql.user;"
